[Kernel Patch] Add switch __get_task_comm() to strscpy() patch for latest kernel
Error Logs:
drivers/hv/dxgkrnl/dxgvmbus.c: In function ‘dxgvmb_send_create_process’:
drivers/hv/dxgkrnl/dxgvmbus.c:693:9: error: implicit declaration of function ‘__get_task_comm’; did you mean ‘__set_task_comm’? [-Wimplicit-function-declaration]
  693 |         __get_task_comm(s, WIN_MAX_PATH, current);
      |         ^~~~~~~~~~~~~~~
      |         __set_task_comm

 * In upper 6.13 kernel, __get_task_comm() has been removed.
 * Switch to __get_task_comm() to strscpy().

Signed-off-by: Yang Jeong Hun <onyxclover9931@gmail.com>