patches: apply eventfd patch to both MAIN and LTS variants of the kernel (#108)
Kernel LTS builds are now failing due to missing eventfd patch

 drivers/hv/dxgkrnl/dxgmodule.c:178:36: error: too many arguments to function call, expected single argument 'ctx', have 2 arguments
  178 |                 eventfd_signal(event->cpu_event, 1);
      |                 ~~~~~~~~~~~~~~                   ^
./include/linux/eventfd.h:87:20: note: 'eventfd_signal' declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^              ~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [scripts/Makefile.build:229: drivers/hv/dxgkrnl/dxgmodule.o] Error 1
make[4]: *** [scripts/Makefile.build:478: drivers/hv/dxgkrnl] Error 2
make[3]: *** [scripts/Makefile.build:478: drivers/hv] Error 2
make[3]: *** Waiting for unfinished jobs....

Signed-off-by: taalojarvi <sreedevan05@gmail.com>