[Kernel Patch] Change __dma_fence_is_later signature in dxgsyncfile (#134)
Error Logs:
drivers/hv/dxgkrnl/dxgsyncfile.c: In function ‘dxgdmafence_signaled’:
drivers/hv/dxgkrnl/dxgsyncfile.c:449:46: error: passing argument 1 of ‘__dma_fence_is_later’ makes pointer from integer without a cast [-Wint-conversion]
  449 |         return __dma_fence_is_later(syncpoint->fence_value, fence->seqno,
      |                                     ~~~~~~~~~^~~~~~~~~~~~~
      |                                              |
      |                                              u64 {aka long long unsigned int}
In file included from ./include/linux/sync_file.h:20,
                 from drivers/hv/dxgkrnl/dxgsyncfile.h:17,
                 from drivers/hv/dxgkrnl/dxgsyncfile.c:36:
./include/linux/dma-fence.h:471:59: note: expected ‘struct dma_fence *’ but argument is of type ‘u64’ {aka ‘long long unsigned int’}
  471 | static inline bool __dma_fence_is_later(struct dma_fence *fence, u64 f1, u64 f2)
      |                                         ~~~~~~~~~~~~~~~~~~^~~~~
drivers/hv/dxgkrnl/dxgsyncfile.c:450:42: error: passing argument 3 of ‘__dma_fence_is_later’ makes integer from pointer without a cast [-Wint-conversion]
  450 |                                     fence->ops);
      |                                     ~~~~~^~~~~
      |                                          |
      |                                          const struct dma_fence_ops *
./include/linux/dma-fence.h:471:78: note: expected ‘u64’ {aka ‘long long unsigned int’} but argument is of type ‘const struct dma_fence_ops *’
  471 | static inline bool __dma_fence_is_later(struct dma_fence *fence, u64 f1, u64 f2)
      |                                                                          ~~~~^~

 * In upper 6.17 kernel, __dma_fence_is_later signature was changed.
 * This commit changes __dma_fence_is_later signature in dxgdmafence_signaled.

Signed-off-by: Yang Jeong Hun <onyxclover9931@gmail.com>